'use client';

import { useEffect, useState } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import type { Account, Budget, Goal, Loan, Transaction } from '@paisapilot/contracts';
import { api, authenticate } from '@/lib/api';
import { formatDate, formatINR } from '@/lib/format';
import { validateImportCsv } from '@/lib/import-validation';

type Domain = 'dashboard' | 'transactions' | 'accounts' | 'investments' | 'budgets' | 'goals' | 'bills' | 'loans' | 'analytics' | 'ai' | 'settings';
const nav: Array<[Domain, string, string]> = [['dashboard', 'Overview', '01'], ['transactions', 'Transactions', '02'], ['accounts', 'Accounts', '03'], ['investments', 'Investments', '04'], ['budgets', 'Budgets', '05'], ['goals', 'Goals', '06'], ['bills', 'Bills', '07'], ['loans', 'Loans', '08'], ['analytics', 'Analytics & health', '09'], ['ai', 'Ask PaisaPilot', '10'], ['settings', 'Settings', '11']];
const titles: Record<Domain, [string, string]> = { dashboard: ['Good morning, Ananya.', 'A clear view of what your money is doing.'], transactions: ['Transactions', 'Every rupee, accounted for.'], accounts: ['Accounts', 'Your financial world, in one place.'], investments: ['Investments', 'Track holdings without the trading noise.'], budgets: ['Budgets', 'Give your monthly spending a shape.'], goals: ['Goals', 'Small, intentional steps add up.'], bills: ['Bills', 'The commitments coming up next.'], loans: ['Loans', 'See the cost and the way out.'], analytics: ['Analytics & health', 'Signals for a steadier financial life.'], ai: ['Ask PaisaPilot', 'A practical answer, grounded in your data.'], settings: ['Settings', 'Control your account and your data.'] };

export default function ProductShell({ initialDomain = 'dashboard', showImport = false }: { initialDomain?: Domain; showImport?: boolean }) {
  const pathname = usePathname(); const router = useRouter(); const domain = (pathname?.split('/')[1] as Domain) || initialDomain;
  const [authed, setAuthed] = useState(false); const [sessionChecked, setSessionChecked] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [data, setData] = useState<Record<string, unknown>>({});
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [register, setRegister] = useState(false); const [prompt, setPrompt] = useState(''); const [answer, setAnswer] = useState('');
  useEffect(() => { api<{ user: { id: string; email: string } }>('/v1/auth/session').then(() => setAuthed(true)).catch(() => setAuthed(false)).finally(() => setSessionChecked(true)); }, []);
  useEffect(() => { if (!authed) return; const endpoint: Record<string, string> = { dashboard: '/v1/summary', transactions: '/v1/transactions', accounts: '/v1/accounts', investments: '/v1/accounts', budgets: '/v1/budgets', goals: '/v1/goals', loans: '/v1/loans', analytics: '/v1/health-score' }; const path = endpoint[domain]; if (!path) { setLoading(false); return; } setLoading(true); setError(''); api<Record<string, unknown>>(path).then(setData).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, [authed, domain]);
  async function signIn(event: React.FormEvent) { event.preventDefault(); setError(''); try { await authenticate(email, password, register ? 'register' : 'login'); setAuthed(true); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not sign in'); } }
  async function ask(event: React.FormEvent) { event.preventDefault(); setAnswer(''); try { const result = await api<{ text: string; label: string; disclaimer?: string }>('/v1/ai/answer', { method: 'POST', body: JSON.stringify({ prompt }) }); setAnswer(`${result.label}: ${result.text}${result.disclaimer ? `\n\n${result.disclaimer}` : ''}`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'AI is unavailable'); } }
  if (!sessionChecked) return <div className="state"><span className="loader" />Loading your workspace...</div>;
  if (!authed) return <main className="auth"><div className="auth-copy"><a className="brand" href="/"><span>PP</span> paisapilot</a><p className="eyebrow">PERSONAL MONEY OS</p><h1>Make your money feel less mysterious.</h1><p>See where it goes, understand what matters, and make the next considered move.</p><a className="auth-privacy" href="/privacy-policy">Privacy policy</a></div><form className="auth-form" onSubmit={signIn}><h2>{register ? 'Create your workspace' : 'Welcome back'}</h2><label>Email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input type="password" minLength={12} required value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error && <p className="error" role="alert">{error}</p>}<button className="button primary">{register ? 'Create account' : 'Sign in'} <span>→</span></button><button type="button" className="link-button" onClick={() => setRegister(!register)}>{register ? 'Already have an account? Sign in' : 'New here? Create an account'}</button><footer className="site-footer auth-footer"><a href="/">PaisaPilot</a><a href="/privacy-policy">Privacy policy</a></footer></form></main>;
  const [title, subtitle] = titles[domain] ?? titles.dashboard; return <div className="app"><aside className="sidebar"><a className="brand" href="/dashboard"><span>PP</span> paisapilot</a><p className="nav-label">WORKSPACE</p><nav>{nav.map(([key, label, number]) => <a className={domain === key ? 'active' : ''} href={`/${key}`} key={key}><b>{number}</b>{label}</a>)}</nav><div className="sidebar-bottom"><a href="/privacy-policy">Privacy policy</a><button className="link-button" onClick={() => { void api('/v1/auth/session', { method: 'DELETE' }).then(() => setAuthed(false)).catch((reason: Error) => setError(reason.message)); }}>Sign out</button></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">FRIDAY, 28 AUGUST 2026</p><h1>{title}</h1><p className="subtitle">{subtitle}</p></div><button className="avatar" aria-label="Account menu">A</button></header>{error && <div className="error-banner">{error}</div>}{loading ? <div className="state"><span className="loader" />Loading your workspace...</div> : <DomainView domain={domain} data={data} prompt={prompt} setPrompt={setPrompt} answer={answer} ask={ask} showImport={showImport} router={router} onAccountsChange={(accounts) => setData((current) => ({ ...current, accounts }))} />}</main></div>;
}

function DomainView({ domain, data, prompt, setPrompt, answer, ask, showImport, router, onAccountsChange }: { domain: Domain; data: Record<string, unknown>; prompt: string; setPrompt: (value: string) => void; answer: string; ask: (event: React.FormEvent) => void; showImport: boolean; router: ReturnType<typeof useRouter>; onAccountsChange: (accounts: Account[]) => void }) {
  const items = (data.accounts ?? data.transactions ?? data.goals ?? data.budgets ?? data.loans) as Array<Account | Transaction | Goal | Budget | Loan> | undefined;
  if (domain === 'accounts') { const accounts = (data.accounts ?? []) as Account[]; return <><AccountForm onCreated={(account) => onAccountsChange([...accounts, account])} />{accounts.length ? <section className="table-wrap"><div className="table-head"><div><p className="eyebrow">LIVE FROM YOUR API</p><h2>{accounts.length} record{accounts.length === 1 ? '' : 's'}</h2></div></div><table><tbody>{accounts.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><span>{item.type.replace(/_/g, ' ')}</span></td><td className="amount">{formatINR(item.balancePaise)}</td></tr>)}</tbody></table></section> : <div className="state empty"><div className="empty-mark">+</div><h2>No accounts yet</h2><p>Add your first account above — bank, cash, card, or wallet.</p></div>}</>; }
  if (domain === 'dashboard') { const summary = data as { incomePaise?: number; expensePaise?: number; netPaise?: number }; return <><section className="hero-grid"><div className="balance"><p className="eyebrow">MONTHLY NET FLOW</p><strong>{formatINR(summary.netPaise ?? 0)}</strong><span className="positive">{(summary.netPaise ?? 0) >= 0 ? '↑' : '↓'} after income and expenses</span></div><div className="insight"><p className="eyebrow">PaisaPilot note</p><h2>Start with one honest month.</h2><p>Add an account and a few transactions to unlock patterns that are actually yours.</p><a href="/transactions" className="text-link">Review activity →</a></div></section><div className="metric-grid"><Metric label="Income" value={formatINR(summary.incomePaise ?? 0)} /><Metric label="Spent" value={formatINR(summary.expensePaise ?? 0)} /><Metric label="Runway" value="Not enough data" muted /></div><section className="section-heading"><div><p className="eyebrow">YOUR NEXT MOVES</p><h2>Build the picture</h2></div><a href="/accounts" className="text-link">View all →</a></section><div className="empty-row"><div><span className="step">01</span><h3>Add your first account</h3><p>Bank, cash, card, or wallet. Manual entry keeps your data in your hands.</p></div><div><span className="step">02</span><h3>Import a statement</h3><p>Bring in a CSV when you are ready. No broker connection required.</p></div><div><span className="step">03</span><h3>Ask a question</h3><p>Use your own numbers as a starting point, not a generic prescription.</p></div></div></>; }
  if (domain === 'ai') return <section className="ai-panel"><p className="eyebrow">CONTEXTUAL Q&A</p><h2>What would you like to understand?</h2><p className="muted">Answers are labeled fact, estimate, or recommendation. Investment content is educational only.</p><div className="prompts"><button onClick={() => setPrompt('How did I spend this month?')}>How did I spend this month?</button><button onClick={() => setPrompt('What should I focus on next?')}>What should I focus on next?</button></div><form onSubmit={ask} className="ask"><input value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Ask about your money..." required maxLength={2000} /><button className="button primary">Ask →</button></form>{answer && <div className="answer">{answer}</div>}</section>;
  if (domain === 'settings') return <Settings />;
  if (domain === 'investments' || showImport) return <ImportPanel accounts={(data.accounts ?? []) as Account[]} />;
  if (domain === 'bills') return <Empty title="Bills will appear here" detail="Add recurring transactions to make upcoming commitments visible." action="Review transactions" href="/transactions" />;
  if (domain === 'analytics') { const score = data as { score?: number; factors?: Record<string, number> }; return <><section className="score"><p className="eyebrow">FINANCIAL HEALTH · VERSION 1</p><strong>{score?.score ?? 0}<small>/100</small></strong><p>Transparent scoring based on cash flow, emergency runway, and debt.</p></section><div className="metric-grid">{Object.entries(score.factors ?? {}).map(([key, value]) => <Metric key={key} label={key.replace(/([A-Z])/g, ' $1')} value={`${Math.round(value * 100)}%`} />)}</div></>; }
  if (!items?.length) return <Empty title={`No ${domain} yet`} detail="This space is ready when you are. Add the first record to make it useful." action={domain === 'accounts' ? 'Add an account' : 'Go to dashboard'} href={domain === 'accounts' ? '/accounts?add=1' : '/dashboard'} />;
  return <section className="table-wrap"><div className="table-head"><div><p className="eyebrow">LIVE FROM YOUR API</p><h2>{items.length} records</h2></div><button className="button secondary">+ Add</button></div><table><tbody>{items.map((item) => <tr key={item.id}><td><strong>{'name' in item ? item.name : item.description}</strong><span>{'occurredOn' in item ? formatDate(item.occurredOn) : 'category' in item ? item.category : 'type' in item ? item.type : ''}</span></td><td className="amount">{'amountPaise' in item ? formatINR(item.amountPaise) : 'balancePaise' in item ? formatINR(item.balancePaise) : 'limitPaise' in item ? formatINR(item.limitPaise) : 'principalPaise' in item ? formatINR(item.principalPaise) : ''}</td></tr>)}</tbody></table></section>;
}
function Metric({ label, value, muted = false }: { label: string; value: string; muted?: boolean }) { return <div className={`metric ${muted ? 'muted' : ''}`}><p>{label}</p><strong>{value}</strong></div>; }
function Empty({ title, detail, action, href }: { title: string; detail: string; action: string; href: string }) { return <div className="state empty"><div className="empty-mark">+</div><h2>{title}</h2><p>{detail}</p><a className="button secondary" href={href}>{action} →</a></div>; }
function Settings() {
  const [status, setStatus] = useState<'idle' | 'working' | 'success' | 'error'>('idle'); const [message, setMessage] = useState('');
  async function exportData() { setStatus('working'); setMessage('Preparing your export...'); try { const result = await api<unknown>('/v1/privacy/export'); const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'paisapilot-export.json'; link.click(); URL.revokeObjectURL(link.href); setStatus('success'); setMessage('Your data export has downloaded.'); } catch (reason) { setStatus('error'); setMessage(reason instanceof Error ? reason.message : 'Could not export your data.'); } }
  async function deleteData() { if (!window.confirm('Permanently delete your PaisaPilot account and data?')) return; setStatus('working'); setMessage('Deleting your account...'); try { await api('/v1/privacy/delete', { method: 'DELETE' }); setStatus('success'); setMessage('Your account and data have been deleted.'); window.setTimeout(() => window.location.assign('/'), 800); } catch (reason) { setStatus('error'); setMessage(reason instanceof Error ? reason.message : 'Could not delete your account.'); } }
  return <section className="settings"><div className="setting-row"><div><h2>Data and privacy</h2><p>Export everything in a portable JSON bundle or permanently delete your account.</p></div><div className="setting-actions"><button className="button secondary" disabled={status === 'working'} onClick={() => void exportData()}>Export JSON</button><button className="button danger" disabled={status === 'working'} onClick={() => void deleteData()}>Delete account</button></div></div>{message && <p className={status === 'error' ? 'status-message error' : 'status-message success'} role={status === 'error' ? 'alert' : 'status'} aria-live="polite">{message}</p>}<div className="setting-row"><div><h2>Product boundaries</h2><p>No live paid integrations, broker connections, advertising, or billing are enabled in V1.</p></div><span className="tag">V1 FREE</span></div><div className="setting-row"><div><h2>Legal</h2><p>Read how PaisaPilot handles the data you choose to store.</p></div><a className="text-link" href="/privacy-policy">Privacy policy →</a></div></section>;
}
function AccountForm({ onCreated }: { onCreated: (account: Account) => void }) {
  const [name, setName] = useState(''); const [type, setType] = useState<Account['type']>('bank'); const [openingBalance, setOpeningBalance] = useState(''); const [status, setStatus] = useState<'idle' | 'submitting' | 'error'>('idle'); const [message, setMessage] = useState('');
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setStatus('submitting'); setMessage('');
    try {
      let balancePaise: number | undefined;
      if (openingBalance.trim()) { const rupees = Number(openingBalance); if (!Number.isFinite(rupees)) throw new Error('Opening balance must be a number.'); balancePaise = Math.round(rupees * 100); }
      const account = await api<Account>('/v1/accounts', { method: 'POST', body: JSON.stringify({ name, type, ...(balancePaise !== undefined ? { balancePaise } : {}) }) });
      onCreated(account); setName(''); setOpeningBalance(''); setType('bank'); setStatus('idle');
    } catch (reason) { setStatus('error'); setMessage(reason instanceof Error ? reason.message : 'Could not add this account.'); }
  }
  return <form className="account-form" onSubmit={submit}><p className="eyebrow">ADD AN ACCOUNT</p><div className="account-form-fields"><label>Name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="HDFC Savings" required maxLength={200} disabled={status === 'submitting'} /></label><label>Type<select value={type} onChange={(event) => setType(event.target.value as Account['type'])} disabled={status === 'submitting'}><option value="bank">Bank</option><option value="cash">Cash</option><option value="credit_card">Credit card</option><option value="upi_wallet">UPI wallet</option><option value="fd">Fixed deposit</option><option value="loan">Loan</option><option value="custom">Custom</option></select></label><label>Opening balance (₹)<input value={openingBalance} onChange={(event) => setOpeningBalance(event.target.value)} placeholder="0" inputMode="decimal" disabled={status === 'submitting'} /></label><button className="button primary" type="submit" disabled={!name.trim() || status === 'submitting'}>{status === 'submitting' ? 'Adding...' : 'Add account →'}</button></div>{message && <p className="status-message error" role="alert">{message}</p>}</form>;
}
function ImportPanel({ accounts }: { accounts: Account[] }) {
  const [csv, setCsv] = useState(''); const [accountId, setAccountId] = useState(''); const [status, setStatus] = useState<'idle' | 'reading' | 'ready' | 'submitting' | 'success' | 'error'>('idle'); const [message, setMessage] = useState('');
  async function chooseFile(selected: File | undefined) { if (!selected) return; if (selected.size > 2_000_000) { setCsv(''); setStatus('error'); setMessage('CSV is too large (maximum 2 MB).'); return; } setStatus('reading'); setMessage(''); try { const contents = await selected.text(); const result = validateImportCsv(contents); setCsv(contents); setStatus('ready'); setMessage(`${result.rows} transaction${result.rows === 1 ? '' : 's'} ready to import.`); } catch (reason) { setCsv(''); setStatus('error'); setMessage(reason instanceof Error ? reason.message : 'Could not read this CSV.'); } }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!csv || !accountId) return; setStatus('submitting'); setMessage('Importing transactions...'); try { const result = await api<{ imported: number }>('/v1/import/transactions', { method: 'POST', body: JSON.stringify({ accountId, csv }) }); setStatus('success'); setMessage(`${result.imported} transaction${result.imported === 1 ? '' : 's'} imported successfully.`); } catch (reason) { setStatus('error'); setMessage(reason instanceof Error ? reason.message : 'Import failed.'); } }
  return <section className="import-panel"><p className="eyebrow">INVESTMENTS / IMPORT</p><h2>Bring a statement into focus.</h2><p className="muted">Import transaction CSVs into an account. Live broker and bank connections are not part of V1.</p><form onSubmit={submit}><label className="account-select">Import into<select value={accountId} onChange={(event) => setAccountId(event.target.value)} required disabled={!accounts.length || status === 'submitting'}><option value="">Choose an account</option>{accounts.map((account) => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label className="file-drop">Choose a CSV statement<input type="file" accept=".csv,text/csv" onChange={(event) => void chooseFile(event.target.files?.[0])} disabled={status === 'submitting'} /></label><p className="fine-print">Required columns: date, description, amount, type. Maximum size: 2 MB. The server validates and deduplicates every import.</p>{!accounts.length && <p className="status-message error" role="alert">Add an account before importing a statement. <a className="text-link" href="/accounts">Add one now →</a></p>}{message && <p className={status === 'error' ? 'status-message error' : 'status-message success'} role={status === 'error' ? 'alert' : 'status'} aria-live="polite">{message}</p>}<button className="button primary" type="submit" disabled={!csv || !accountId || status === 'reading' || status === 'submitting'}>{status === 'submitting' ? 'Importing...' : 'Import transactions →'}</button></form></section>;
}